# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BraydenManikinManager-Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
   pod 'AlamofireObjectMapper', '5.0.0'
   pod 'Alamofire', '4.8.2' 
  pod 'SwiftyJSON' 
  pod 'RxBluetoothKit' #, :git => 'https://github.com/Polidea/RxBluetoothKit.git', :branch => 'swift4'                                                                                                                                                                                                                                                                                                                                
  pod 'iOSDFULibrary'
 
  # Pods for BraydenManikinManager-Example

  target 'BraydenManikinManager-ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BraydenManikinManager-ExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
